spring.application.name=booking
server.port = 5431

spring.datasource.url = jdbc:postgresql://localhost:5432/project
spring.datasource.username = postgres
spring.datasource.password = 0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = create
spring.jpa.show-sql = true